### ISSUE TITLE
[Suggestion] Blacklisting Blocks

### ISSUE THREAD

**Issue by Syhlo** [SolidBlock-cn/extshape#11]
I'm not sure how feasible/difficult it would be but it'd be cool if there was a configuration file where people could blacklist certain blocks (i.e. an array of block ids to blacklist). Blacklisting a block would prevent the block and its recipe from registering when the mod initializes.

For example, I have some custom recipes on my server (Packed Ice -> Ice being one of them) that conflicts with ExtShape recipes (i.e. Packed Ice Button). Being able to share a config with the players on my server that blacklists blocks with recipe conflicts would be amazing.

Thanks for the mod :)

**Comment by SolidBlock-cn** [comment]
At present I have no plan of configuring which blocks to make. You can block the recipes that conflict yours with datapacks.

**Comment by Syhlo** [comment]
Thanks for the quick reply, I'll look into that. :)
