### ISSUE TITLE
Both Pumpkin, and Melon buttons conflict with vanilla recipes

### ISSUE THREAD

**Issue by ClaudiusMinimus** [SolidBlock-cn/extshape#12]
Both Pumpkin, and Melon buttons conflict with vanilla recipes for getting pumpkin seeds and melon slices

Minecraft 1.18 Fabric
extshape-1.3.1-mc1.17+.jar

While this issue is somewhat related to issue [11](https://github.com/SolidBlock-cn/extshape/issues/11) the main difference is these are vanilla blocks

**Comment by Syhlo** [comment]
There's a mod called "Polymorph" that resolves recipe conflicts by letting you choose the result in the crafting window. Might be worth checking out. :P

**Comment by ClaudiusMinimus** [comment]
Thank you for the suggestion. At the time of this issue report polymorph
had not been ported to 1.18 yet. I added it to all of my modpacks as soon
as it was released.

The real issue is a mod such as this should not have recipes that conflict
with vanilla.

Kind regards,
CM

**Comment by SolidBlock-cn** [comment]
Fixed.
