### ISSUE TITLE
Refusing to Run

### ISSUE THREAD

**Issue by TheeSplatt** [SolidBlock-cn/extshape#13]
When i attempt to run it in 1.16.5 with the lib and fabric loader it refuses to run

**Comment by SolidBlock-cn** [comment]
Could you please provide any detailed informations, like loader messages or crash reports?
This mod requires Fabric API and ARRP mod.

**Comment by TheeSplatt** [comment]
This is a part in the crash report that said the problem, but I don't know what it means. I have all the right things: fabric loader 0.12.5, fabric api, arrp lib, but it gives me exit code -1. java.lang.NoSuchMethodError: net.devtech.arrp.api.RuntimeResourcePack.create(Lnet/minecraft/class_2960;)Lnet/devtech/arrp/api/RuntimeResourcePack

**Comment by SolidBlock-cn** [comment]
OK I'll look into it.

**Comment by TheeSplatt** [comment]
Found the problem. i got it to load up minecraft, i was using the wrong version of ARRP.  but now when i try to load a world, it gets stuck at 54% on loading and then it crashes.

**Comment by SolidBlock-cn** [comment]
Try to press F3+C for ten seconds and find the crash-report. If the game does not crash, you can find `latest.log` in the `logs` folder.

**Comment by SolidBlock-cn** [comment]
The mod has updated just now. Since this version 1.5.0 it relies on BRRP instead of ARRP. If you still find the problem, please provide crash report and reopen the issue.
