### ISSUE TITLE
Make more block Rotatable with Wrench Mod

### ISSUE THREAD

**Issue by ardissaps** [SolidBlock-cn/extshape#15]
Currently some block cant be rotated  (vertical stair), while other can already be rotated (regular stair, vertical)

**Comment by SolidBlock-cn** [comment]
I remember vertical stairs can be rotated correctly through structure blocks via `rotate` method. Maybe Wrench Mod does not invoke the `rotate` method? I'll look into it.

**Comment by ardissaps** [comment]
> I remember vertical stairs can be rotated correctly through structure blocks via `rotate` method. Maybe Wrench Mod does not invoke the `rotate` method? I'll look into it.

Could be, I have wrench 1 from Charm and 1 from Minekea.

**Comment by SolidBlock-cn** [comment]
I suggest it is the issue of Wrench Mod not using the `rotate` method. Could you provide the link of that mod?

**Comment by ardissaps** [comment]
Charm :
https://modrinth.com/mod/Charm

Minekea :
https://www.curseforge.com/minecraft/mc-mods/minekea-fabric

**Comment by SolidBlock-cn** [comment]
I'm not sure which wrench you're referring to.

**Comment by ardissaps** [comment]
> I'm not sure which wrench you're referring to.

Those mod include item wrench brown one is from Charm mod, while silver Minekea : 
https://imgur.com/a/O6OlY0I

**Comment by SolidBlock-cn** [comment]
That mod uses properties that exist in vanilla, instead of those in this mod. I have no plan to make it rotatable with wrench.
