### ISSUE TITLE
Conflicting recipes for trap doors and wood walls

### ISSUE THREAD

**Issue by BrunoLiddell** [SolidBlock-cn/extshape#17]
Hello!

Thank you for this amazing addon to the vanilla blocks, it's super in depth!

However, there's seems to be a conflict in the recipes of wood trap doors (vanilla) and the wood walls from the mod:

![extshape_issue_trap-door](https://user-images.githubusercontent.com/57353858/173060852-360d1cc5-16ae-40d1-8a16-466d69f3c9c2.jpg)
![extshape_issue_wood-wall](https://user-images.githubusercontent.com/57353858/173060853-799aacd5-bbff-4b25-8420-1ccee76d2b11.jpg)

The normal recipe for vanilla walls (the ones made with stone) are like this instead:

![extshape_issue_wall-recipe](https://user-images.githubusercontent.com/57353858/173061110-3f520b91-c58b-4e7b-8870-148b96991f6f.jpg)

I should mention that using this pattern (6 blocks on the bottom rows) to craft a wood wall also works to craft the wood wall.

I hope you can fix this issue :) Thanks again for this awesome mod!

**Comment by SolidBlock-cn** [comment]
Thank you for the information. I'll fix it in the next version.

**Comment by ardissaps** [comment]
> Hello!
> 
> Thank you for this amazing addon to the vanilla blocks, it's super in depth!
> 
> However, there's seems to be a conflict in the recipes of wood trap doors (vanilla) and the wood walls from the mod:
> 
> ![extshape_issue_trap-door](https://user-images.githubusercontent.com/57353858/173060852-360d1cc5-16ae-40d1-8a16-466d69f3c9c2.jpg) ![extshape_issue_wood-wall](https://user-images.githubusercontent.com/57353858/173060853-799aacd5-bbff-4b25-8420-1ccee76d2b11.jpg)
> 
> The normal recipe for vanilla walls (the ones made with stone) are like this instead:
> 
> ![extshape_issue_wall-recipe](https://user-images.githubusercontent.com/57353858/173061110-3f520b91-c58b-4e7b-8870-148b96991f6f.jpg)
> 
> I should mention that using this pattern (6 blocks on the bottom rows) to craft a wood wall also works to craft the wood wall.
> 
> I hope you can fix this issue :) Thanks again for this awesome mod!

Use polymorph so you can choose result from the same recipe with button.
https://www.curseforge.com/minecraft/mc-mods/polymorph-fabric

**Comment by SolidBlock-cn** [comment]
Fixed in 1.5.2.
