### ISSUE TITLE
What does Register Block Family mean? [Modlist Screenshot Included]

### ISSUE THREAD

**Issue by ardissaps** [SolidBlock-cn/extshape#19]
Should I enable it or not if have these mods :
![1](https://user-images.githubusercontent.com/82106625/175493935-2ae9c29f-03fb-4eab-8c19-1b032059959c.jpg)
![2](https://user-images.githubusercontent.com/82106625/175493959-67e6cf63-707c-4043-bc44-996f3dbdb958.jpg)

**Comment by SolidBlock-cn** [comment]
Usually you do not need it.

**Comment by ardissaps** [comment]
@SolidBlock-cn it is default ON, should I turned it OFF if I play on heavily modded minecraft?
