### ISSUE TITLE
Crash at startup

### ISSUE THREAD

**Issue by emmzrig** [SolidBlock-cn/extshape#2]
[crash-2021-09-03_17.11.40-client.txt](https://github.com/SolidBlock-cn/extshape/files/7104845/crash-2021-09-03_17.11.40-client.txt)

**Comment by SolidBlock-cn** [comment]
Thanks for noticing. I'll check it.

**Comment by SolidBlock-cn** [comment]
Could you please also provide a game output file, which is located in `.minecraft\logs` folder?

**Comment by SolidBlock-cn** [comment]
Fixed at release 1.2.2.
