### ISSUE TITLE
Some block does not Have sound with Presence of the Footsep

### ISSUE THREAD

**Issue by ardissaps** [SolidBlock-cn/extshape#21]
Not all but some as example :
Melon stairs have sound but not gold stair and many others like wall.
[Presence of the Footstep](https://www.curseforge.com/minecraft/mc-mods/presence-footsteps).

**Comment by SolidBlock-cn** [comment]
Perhaps Presence of the Footstep only recognizes vanilla blocks. I have no plan to fix it.
