### ISSUE TITLE
Conflict with create 0.5e

### ISSUE THREAD

**Issue by AndeCCCCC** [SolidBlock-cn/extshape#22]
Registry entry not present: create:copper_shingles
[crash-2022-10-15_20.09.27-fml.txt](https://github.com/SolidBlock-cn/extshape/files/9792035/crash-2022-10-15_20.09.27-fml.txt)

**Comment by SolidBlock-cn** [comment]
I have noticed the issue. Thanks for the information. I'll fix it when feasible.
