### ISSUE TITLE
Crash on server startup

### ISSUE THREAD

**Issue by rohanverma2007** [SolidBlock-cn/extshape#24]
the server just crashes on startup with this mod installed
[crash-2023-02-17_21.09.24-fml.txt](https://github.com/SolidBlock-cn/extshape/files/10771737/crash-2023-02-17_21.09.24-fml.txt)

**Comment by rohanverma2007** [comment]
this on the forge side

**Comment by SolidBlock-cn** [comment]
ok I'll look into that.

**Comment by SolidBlock-cn** [comment]
You're using outdated version of Extended Block Shapes mod. This issue should not happen for the latest version.
