### ISSUE TITLE
Flickers when showing things in container

### ISSUE THREAD

**Issue by Rad586** [SolidBlock-cn/extshape#26]
Game version: 1.18.2 fabric
Mod version: 1.8.0
Description: It flickers when showing things in container(chests, villager gui, etc). It seems be a performance issue due to the gerneration of 3983 advancements(reported by m-tweaks dev).

**Comment by SolidBlock-cn** [comment]
Generation of advancements does not seem to take place when opening container. If you persist this is a bug, feel free to reopen the post.
