### ISSUE TITLE
extshape 2.0 crashes on Quilt, 1.19.4

### ISSUE THREAD

**Issue by dizzydizzee** [SolidBlock-cn/extshape#28]
Using Extended block shapes 2.0.0 crashes minecraft 1.19.4 before the game manages to startup

Have tested on all other mods I use and it is definitely this mod (not BRRP either). Tested on Fabric for 1.19.4 and it works fine, but on Quilt it crashes.

Crash log (check line 568): [https://paste.ee/p/yJQy8](https://paste.ee/p/yJQy8)

Using MultiMC launcher, Quilt loader 0.18.10 (with quilted fabric api)

Thank you!

**Comment by SolidBlock-cn** [comment]
It is a compatibility issue of Quilt. I think Quilt (of the version you used) was not really compatible with Fabric's `FlammableBlockRegistry`. Therefore, I think it should be Quilt's problem.
Unfortunately, I currently have no plan to make it compatible with Quilt.
