### ISSUE TITLE
Trapdoors Broken

### ISSUE THREAD

**Issue by xanthian** [SolidBlock-cn/extshape#3]
Can no longer make trapdoors
![Screenshot 2021-09-06 224328](https://user-images.githubusercontent.com/7688001/132262006-1c956fd1-b619-4613-afff-d795f6261ac3.jpg)
, as it tries to make wall instead.

**Comment by SolidBlock-cn** [comment]
Thanks for the post. Please note that wooden walls may be removed entirely in future versions.
