### ISSUE TITLE
[Suggestion] Blocks via /give?

### ISSUE THREAD

**Issue by viiuan** [SolidBlock-cn/extshape#30]
Would it be possible to add the ability to /give blocks from this mod?

**Comment by SolidBlock-cn** [comment]
Idk what you mean. Can't the blocks be given from `/give`?

**Comment by viiuan** [comment]
As far as I can see, no :( I can test again but yeah every time I've tried nothing comes up and I have to go into creative mode to get blocks

**Comment by SolidBlock-cn** [comment]
Seems strange. They should appear in command suggestions. Make sure the block or item ids begin with `extshape:`.

**Comment by viiuan** [comment]
I don't know what i was doing before, but it seems to be working now. Looks like I might have needed to type in that `extshape:` at the start and I didn't know!
