### ISSUE TITLE
Crash On load

### ISSUE THREAD

**Issue by A5ho9999** [SolidBlock-cn/extshape#31]
Game crashes on load with POLISHED_AMEHTYST

Fabric 1.19.4

https://gist.github.com/A5ho9999/c74f03c295078b68be73fb8ffe2d4ef8

**Comment by SolidBlock-cn** [comment]
Please try the latest version of "Extended Block Shapes - Blockus" that I've uploaded just now. It should have been fixed.

**Comment by A5ho9999** [comment]
Yup all good now, thank you
