### ISSUE TITLE
Incompatibility w/ Quilt Mod Loader?

### ISSUE THREAD

**Issue by viiuan** [SolidBlock-cn/extshape#33]
I have recently tried switching to using the Quilt mod loader as some mods I want to use can only be used with Quilt from MC v1.20 onwards.
Quilt is supposed to work with Fabric mods, but when I try to play with extshape in my Quilt installation, it crashes the game on startup.
I start the game through the Prism Launcher if that makes a difference.
It does not crash when I only have BRRP in my mods folder, only when extshape is in there.

My crash log is attached.
[crash-2023-06-11_14.23.54-client.txt](https://github.com/SolidBlock-cn/extshape/files/11715468/crash-2023-06-11_14.23.54-client.txt)

**Comment by SolidBlock-cn** [comment]
Duplicate of #28

Unfortunately, currently I have no plan to make it compatible with Quilt. This may be an issue of Quilt because it states that it's compatible with Fabric mods.

**Comment by viiuan** [comment]
Sorry, I didn't realize someone also commented on this issue before!
However, that's understandable. I would be happy to see it eventually on Quilt then, but I understand that maintaining and updating this mod must be a lot of work. I'll try to figure out what's best on my end.
