### ISSUE TITLE
Nothing Happened in forge version

### ISSUE THREAD

**Issue by LP222222** [SolidBlock-cn/extshape#34]
![Uploading 2023-06-26_12.57.07.png…]()
![2023-06-26_13 01 03](https://github.com/SolidBlock-cn/extshape/assets/110199722/fd49033c-1e7b-41c9-89c7-a2fdf0a2615b)

**Comment by LP222222** [comment]
![2023-06-26_12 57 07](https://github.com/SolidBlock-cn/extshape/assets/110199722/7764bf90-0047-4917-9b9b-b49413e79739)
Missing

**Comment by SolidBlock-cn** [comment]
Well it is so strange.
Could you please tell me the Minecraft version, or provide a log (in the `logs` directory)?

**Comment by SolidBlock-cn** [comment]
It should be fixed now. Please try 2.0.5 for Forge which I released just now. If it still happens, please reopen this post.
