### ISSUE TITLE
Game crashes when opening the creative inventory

### ISSUE THREAD

**Issue by leaowg** [SolidBlock-cn/extshape#36]
I'm using the mod (extended block shapes) and its dependent (BRRP) with Forge 1.19.4, and it crashes whenever I open the creative inventory. Am I doing something wrong? I downloaded the files from both curseforge and modrinth respectively, and have tried the older version of BRRP and have gotten the same result. I am not using any other mods. I don't believe I am using any other modifiers that affect Minecraft either. How can I fix this?

![Screenshot_1](https://github.com/SolidBlock-cn/extshape/assets/140367566/75a1eda6-5564-4bd8-bf16-8473d6d20a57)
![Screenshot_2](https://github.com/SolidBlock-cn/extshape/assets/140367566/9ce00ffb-39d5-45ce-81ef-0a2800faf00a)
[crash-2023-07-23_21.04.43-client.txt](https://github.com/SolidBlock-cn/extshape/files/12141621/crash-2023-07-23_21.04.43-client.txt)

**Comment by SolidBlock-cn** [comment]
It seems my fault. Thanks for the report. I'll fix it within several days.

**Comment by SolidBlock-cn** [comment]
Please try the lastest 2.0.5 for Forge 1.19.4.
