### ISSUE TITLE
Villager pathfinding error

### ISSUE THREAD

**Issue by fulminon** [SolidBlock-cn/extshape#37]
The villagers do not see the mod blocks and therefore try to pass through them, which stops them in their path. The error occurs in 1.19.4. On the linked image, the villager jumps on the spot, trying to pass the quarter block.
![2023-08-07_15 30 13](https://github.com/SolidBlock-cn/extshape/assets/19209614/11cdfe2e-bd9b-4453-8ba3-2896fd025a6e)

**Comment by SolidBlock-cn** [comment]
Can't make sure that is the bug of the mod. If you persists please reopen.

**Comment by CoffeeDonkey** [comment]
Hi, i have also encountered this bug. Swapping out the vertical slabs from extshape with ones from a different mod fixes the issue, so it is an extshape bug.

On closer inspection, the difference between the extshape slab and the other mod seems to be a option called "single_slab: true". Extshape slab does not have this option at all.

**Comment by SolidBlock-cn** [comment]
Thanks for the report. It will be fixed in the next version.
