### ISSUE TITLE
Polished blackstone vertical slab doesn't have tool speed/drop assigned

### ISSUE THREAD

**Issue by AdamBrezik** [SolidBlock-cn/extshape#38]
When using pickaxe on vertical polished blackstone slab, mining takes as long as it'd take by hand and I don't get any drop.

**Comment by SolidBlock-cn** [comment]
Do you mean polished blackstone bricks? I'll fix it soon.

**Comment by AdamBrezik** [comment]
Hello,

    Yes, exactly, sorry. Didn't report it straight from the game and my
note was a cryptic one. Thank you for your understanding.

Kind regards,

A#
