### ISSUE TITLE
Obsidian and crying obsidian stairs, slabs and vertical slabs can be pushed by a piston.

### ISSUE THREAD

**Issue by RandomGamerj** [SolidBlock-cn/extshape#39]
I don't know if this is a feature, but obsidian and crying obsidian counterparts sould not be able to be pushed by pistons as far as I think. I don't know if this is possible or not, but would be a great feature
Cheers..:)

**Comment by SolidBlock-cn** [comment]
It's confirmed that many blocks in this mod have issues related to piston behavior. Thanks for your notice. I will fix it in the next version.
