### ISSUE TITLE
Direction of wood log texture for stairs

### ISSUE THREAD

**Issue by MrTheRich** [SolidBlock-cn/extshape#42]
Is it possible to make the log and wood stairs have their texture direction changed too?
I know it's possible for the new slabs to have the texture of the log cut part face to the side. But i'd like to have the same for stairs and quarter blocks. I don't know if it's easy to do, since stairs also depend on where you click to place them just like the normal log blocks.

**Comment by SolidBlock-cn** [comment]
Unfortunately, it's not that easy and I have no plan to complete that.
