### ISSUE TITLE
Crashes with wilder wild on 1.20.6 and 1.21

### ISSUE THREAD

**Issue by nickademas** [SolidBlock-cn/extshape#46]
[latest.log](https://github.com/SolidBlock-cn/extshape/files/15284253/latest.log)

**Comment by SolidBlock-cn** [comment]
It seems the log did not provide any info about the crash

**Comment by makumaku1974** [comment]
[crash-2024-06-21_17.47.41-client.txt](https://github.com/user-attachments/files/15926215/crash-2024-06-21_17.47.41-client.txt)

This do in 1.21

I already also [reported this conflict](https://github.com/FrozenBlock/WilderWild/issues/391) with the Wilder Wilds mod. It seems to not detect on mc logs but the crash report log did for me.

**Comment by SolidBlock-cn** [comment]
The issue lies on invoking `BuiltinRegistries.createWrapperLookup()`. I'll check how to fix it.

**Comment by SolidBlock-cn** [comment]
Please try version [1.0.4-beta.1 or Better RRP mod](https://github.com/SolidBlock-cn/BRRP/releases/tag/v1.0.4-beta.1) I released just now.

Minecraft's Registry system is too complicated and I still cannot figure out where the real issue lies. The issue happens on `BuiltinRegistries.createWrapperLookup()` (official name `VanillaRegistries.createLookup`), and reported errors of unreferenced keys. I bypassed that checking process in my mod.

**Comment by makumaku1974** [comment]
imma try testing it right now.

**Comment by makumaku1974** [comment]
> Please try version [1.0.4-beta.1 or Better RRP mod](https://github.com/SolidBlock-cn/BRRP/releases/tag/v1.0.4-beta.1) I released just now.
> 
> Minecraft's Registry system is too complicated and I still cannot figure out where the real issue lies. The issue happens on `BuiltinRegistries.createWrapperLookup()` (official name `VanillaRegistries.createLookup`), and reported errors of unreferenced keys. I bypassed that checking process in my mod.

It works well even for a beta.

**Comment by makumaku1974** [comment]
> Please try version [1.0.4-beta.1 or Better RRP mod](https://github.com/SolidBlock-cn/BRRP/releases/tag/v1.0.4-beta.1) I released just now.
> 
> Minecraft's Registry system is too complicated and I still cannot figure out where the real issue lies. The issue happens on `BuiltinRegistries.createWrapperLookup()` (official name `VanillaRegistries.createLookup`), and reported errors of unreferenced keys. I bypassed that checking process in my mod.

Umm developer. What could this mean since I didn't expect this one also from Wilder Wild.

You see. I've installed this mod with the new BRRP beta alongside with Wilder Wild. It seems fine at first but this time droplets are appearing with every biome.
![2024-07-06_13 50 51](https://github.com/SolidBlock-cn/extshape/assets/129804277/2dff894d-c26b-4cc6-940d-c5c5b2079f47)

This is when Wilder Wild is off.
![2024-07-06_18 48 38](https://github.com/SolidBlock-cn/extshape/assets/129804277/6d33edb1-ef3b-4431-a5d2-1f49076be355)

**Comment by SolidBlock-cn** [comment]
> > Please try version [1.0.4-beta.1 or Better RRP mod](https://github.com/SolidBlock-cn/BRRP/releases/tag/v1.0.4-beta.1) I released just now.
> > Minecraft's Registry system is too complicated and I still cannot figure out where the real issue lies. The issue happens on `BuiltinRegistries.createWrapperLookup()` (official name `VanillaRegistries.createLookup`), and reported errors of unreferenced keys. I bypassed that checking process in my mod.
> 
> Umm developer. What could this mean since I didn't expect this one also from Wilder Wild.
> 
> You see. I've installed this mod with the new BRRP beta alongside with Wilder Wild. It seems fine at first but this time droplets are appearing with every biome. ![2024-07-06_13 50 51](https://private-user-images.githubusercontent.com/129804277/346268700-2dff894d-c26b-4cc6-940d-c5c5b2079f47.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjEwOTY3ODksIm5iZiI6MTcyMTA5NjQ4OSwicGF0aCI6Ii8xMjk4MDQyNzcvMzQ2MjY4NzAwLTJkZmY4OTRkLWMyNmItNGNjNi05NDBkLWM1YzViMjA3OWY0Ny5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzE2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcxNlQwMjIxMjlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wMzIzYmUzODIwYjRhMDEzNmZkZDAwNDZjMTdhY2ZjNzg0MWJlYzhlYzljY2YyM2EzODlhNTI4ZjI5MmQ5ZDc0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.bC5Hv_A6O1olZoGVUva1mU6T80u0W6zMBZphXz09Fho)
> 
> This is when Wilder Wild is off. ![2024-07-06_18 48 38](https://private-user-images.githubusercontent.com/129804277/346268705-6d33edb1-ef3b-4431-a5d2-1f49076be355.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjEwOTY3ODksIm5iZiI6MTcyMTA5NjQ4OSwicGF0aCI6Ii8xMjk4MDQyNzcvMzQ2MjY4NzA1LTZkMzNlZGIxLWVmM2ItNDQzMS1hNWQyLTFmNDkwNzZiZTM1NS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzE2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcxNlQwMjIxMjlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xOThmNWRhN2IzYjk3Zjc3MmQzMTk4MjNmODUzYTBjZGIyZjlkZDJmYTVlMDFiNjg3ZjFmNmZlY2IwMTcyYTQ2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.00bIinU098KEC9zb3KCfAY_gUbv-1HfjTOgUpWbO_6U)

I didn't reproduce the droplets in every biome. I'm using Minecraft 1.21, BRRP v1.0.4-beta.1, Wilder Wild 2.4.6, Fabric API 0.100.7 and Fabric Loader 0.15.11. Could you help reproducing the issue in your screenshot?

**Comment by makumaku1974** [comment]
im on 0.16.0 and still works but the problem is that mixins confuses other codes resulting to also other mods be incompatible with Wilder Wild. But i would show a video and screenshots.

**Comment by makumaku1974** [comment]
Update: It is actually fix but maybe some of the mods could conflict it? Could you check blockus alongside   with your other mod ext blockus? But i'll check it with Biome's O Plenty

**Comment by SolidBlock-cn** [comment]
Do issues still happen now?

**Comment by SolidBlock-cn** [comment]
Since the issue seems to be fixed, as the library mod BRRP has been updated before in order to fix the conflict, this issue will be closed.
If you run into the issue again, please re-open it.
