### ISSUE TITLE
在服务器中踩踏羊毛压力板会造成玩家强制退出游戏

### ISSUE THREAD

**Issue by Emerald-Rail** [SolidBlock-cn/extshape#47]
如标题，提示的内容为![image](https://github.com/SolidBlock-cn/extshape/assets/168388244/8a9c4ac0-4ec1-4394-862d-41d56682b623)

**Comment by SolidBlock-cn** [comment]
能提供下服务器和客户端的日志吗？我在本地没有复现此问题。另请确保服务器和客户端安装的是同一模组版本。
