### ISSUE TITLE
How and why is this like that

### ISSUE THREAD

**Issue by idenher1o** [SolidBlock-cn/extshape#49]
I got this exact error which says that the mod for 1.20.6 is incompatible with mionecraft version 1.20.6? how?

Incompatible mods found!
net.fabricmc.loader.impl.FormattedException: Some of your mods are incompatible with the game or each other!
A potential solution has been determined, this may resolve your problem:
	 - Replace mod 'Extended Block Shapes' (extshape) 2.1.4-mc1.20.6 with any version that is compatible with:
		 - minecraft 1.20.6
More details:
	 - Mod 'Extended Block Shapes' (extshape) 2.1.4-mc1.20.6 requires version 1.20.5-1.20.6 of 'Minecraft' (minecraft), but only the wrong version is present: 1.20.6!
	at net.fabricmc.loader.impl.FormattedException.ofLocalized(FormattedException.java:51)
	at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:195)
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:146)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

**Comment by SolidBlock-cn** [comment]
My fault. I’ll fix it as soon as I can.

**Comment by SolidBlock-cn** [comment]
I released a new version to fix that. Please check that.

**Comment by idenher1o** [comment]
I dont see any new version? It's still 2.1.4-mc1.20.6

**Comment by idenher1o** [comment]
THANK you so much it worked. Literally one of my favorite mods ever! Thanks again!
