### ISSUE TITLE
[Feature] Add Stained Glass 1.20.1

### ISSUE THREAD

**Issue by iPanic-Dev** [SolidBlock-cn/extshape#50]
## What
* Add support for stained glass (vanilla) for vertical stairs, slabs, etc
* Add support for regular clear glass
* Add support for tinted glass

## Why
Glass is a vital piece of many builds. Having the flexibility for transparent vertical pieces would greatly improve builds. There is also very few other tools available that can add vertical glass pieces

Thank you for your consideration.

**Comment by SolidBlock-cn** [comment]
Transparent blocks work differently and require extra work, so I have no plan adding them. However, you may take a look at [Mod Glass](https://modrinth.com/mod/mo-glass) mod.
