### ISSUE TITLE
Incompatibility with Sounds

### ISSUE THREAD

**Issue by Eclipse-Sol** [SolidBlock-cn/extshape#54]
This issue started on Sounds' GitHub page, however it seems that it might be something that needs to be addressed here.

Currently, Extended Block Shapes crashes with Sounds due to an issue regarding the YACL version. It was recommended that the YACL implementation is updated to return compatibility with Sounds.

Crash Log: https://mclo.gs/iDOlieC

It was also noted that YACL v2 was deprecated over a year ago.

https://github.com/IMB11/Sounds/issues/81

**Comment by makumaku1974** [comment]
are you using a new version

**Comment by Eclipse-Sol** [comment]
I'm using the latest version of your mod and Sounds.

**Comment by makumaku1974** [comment]
> I'm using the latest version of your mod and Sounds.

could you check BRRP version. Btw I do not own the mod.

This is the link that will get you to the beta version of BRRP 1.0.4
https://github.com/SolidBlock-cn/extshape/issues/46#issuecomment-2210310337

**Comment by Eclipse-Sol** [comment]
I apologize, I should have mentioned I'm using Minecraft version 1.20.1. 

EDIT: Turns out that it crashes anyway using the respective 1.20.6 versions of the mods and using the beta BRRP mod.

Crash Log: https://mclo.gs/wEMKYHj

**Comment by makumaku1974** [comment]
> I apologize, I should have mentioned I'm using Minecraft version 1.20.1.
> 
> EDIT: Turns out that it crashes anyway using the respective 1.20.6 versions of the mods and using the beta BRRP mod.
> 
> Crash Log: https://mclo.gs/wEMKYHj

I really cant help you since I do not own the mod, and im currently on 1.21 so wait for the mod dev to assist u.

**Comment by SolidBlock-cn** [comment]
If they mean [YetAnotherConfigLib mod](https://modrinth.com/mod/yacl) by saying YACL, my mod does not use it at all.

The issue perhaps happens because my mod is initialized before Sounds mod, while I called `AbstractBlock.getSoundGroup()` in my initialization stage. The Sounds mod [injected a mixin](https://github.com/IMB11/Sounds/blob/main/src/main/java/dev/imb11/sounds/mixin/BlockSoundMixin.java) to it, while it seems that mod is not initialized yet, causing the issue.

Unfortunately, I have no idea about how to fix that.

**Comment by SolidBlock-cn** [comment]
I didn't test, but the issue seems not to happen, because I discover in the [Sounds mod](https://github.com/IMB11/Sounds/blob/main/src/main/java/dev/imb11/sounds/mixin/BlockSoundMixin.java), the exception has been caught.

**Comment by Eclipse-Sol** [comment]
Looks like Sounds did actually update to fix this crash. Sorry about all of this! Will close as fixed.
