### ISSUE TITLE
[Enhancement] Please add glass versions...

### ISSUE THREAD

**Issue by makumaku1974** [SolidBlock-cn/extshape#55]
I think glass is really neglected... And it is a great use within your mod.
![image](https://github.com/user-attachments/assets/08c212ec-0611-41f4-8d8d-2d25353d731a)

**Comment by SolidBlock-cn** [comment]
I have no plan to add glasses. Transparent blocks work quite differently. You may see [Mo Glass](https://modrinth.com/mod/mo-glass) mod for that.
