### ISSUE TITLE
Stripping Mangrove Log Stairs/Slabs/Quarter Pieces causes them to become Stripped OAK variants.

### ISSUE THREAD

**Issue by LocutusOfNord** [SolidBlock-cn/extshape#56]
Good morning.
We're enjoying version 2.1.4 of your mod in a Minecraft 1.21 SMP running on Fabric 0.16.0.
One of the players has noticed that stripping any Mangrove Log blocks (stairs, sideways stairs, slabs, quarter pieces, etc…) causes them to become a Stripped OAK version of that block.
We've tested other wood types, and Mangrove Log is the only one we've found exhibiting this problem. The other wood logs do not seem to have this issue, and mangrove wood does not either.
Thanks!
(And by the way, we'd LOVE to see glass, magma, slime, and grass block shapes added)

**Comment by SolidBlock-cn** [comment]
I've reproduced the issue. I'll fix soon.

**Comment by LocutusOfNord** [comment]
Thanks!
