### ISSUE TITLE
[Request] Block Additions

### ISSUE THREAD

**Issue by xanthian** [SolidBlock-cn/extshape#6]
Please consider adding the following block types, absolutely take your time and no pressure, loving the mod, just pointing out some blocks that would be a welcome addition!

Blackstone
Polished Blackstone
Chiselled Polished Blackstone
Gilded Blackstone
Basalt
Polished Basalt
Deepslate
Chiselled Deepslate
Dripstone Block
Warped Nylium
Warped Stem
Chiselled Nether Brick
Chiselled Stone Brick
Quartz Pillar
Quartz Brick
Chiselled Sandstone
All the Glazed Terracotta (White, Orange, Yellow, Light Blue, Lime, Pink, Magenta, Grey, Light Grey, Cyan, Purple, Blue, Brown, Green, Red, Black)

Possibly more, but these are ones that come to mind initially.

**Comment by SolidBlock-cn** [comment]
Thanks for the suggestion. Some I'll add. Some blocks are directional, of which it's not convenient to add shapes. Btw, glazed terracotta is a little complex and it has slabs currently.

**Comment by SolidBlock-cn** [comment]
Added some.
