### ISSUE TITLE
縱條功能請求

### ISSUE THREAD

**Issue by specialTT** [SolidBlock-cn/extshape#62]
我很希望橫條和縱條能夠在一個方塊內放置多個，就像半磚那樣，拜託了。

**Comment by SolidBlock-cn** [comment]
叠加横条和纵条方块的实现会比较复杂，且会修改原有行为，暂不考虑，敬请谅解。

**Comment by specialTT** [comment]
那麼可以添加斜對角橫條嗎？就是有兩個橫條在斜對角，然後在一個方塊內，這樣子就能實現以1/2×1/2格方塊為一個像素建構像素字了。

**Comment by SolidBlock-cn** [comment]
如果想要构造像素字的话，建议使用类似雕凿或者方块建模之类的模组。

**Comment by specialTT** [comment]
ok
