### ISSUE TITLE
漢化增加

### ISSUE THREAD

**Issue by specialTT** [SolidBlock-cn/extshape#63]
求柵欄和牆的漢化！

**Comment by SolidBlock-cn** [comment]
栅栏和墙在游戏内仍显示的是英文吗？

**Comment by specialTT** [comment]
是的，但顯示的是本地化鍵名

**Comment by SolidBlock-cn** [comment]
是本模组的所有的栅栏和墙都显示为本地化键名吗？我这里还无法复现。使用的什么游戏版本和模组版本？

**Comment by specialTT** [comment]
是的，我用的是1.21+2.2.2，其實在mc百科上也有人會表達這樣的問題。
![螢幕擷取畫面 2024-09-20 181657](https://github.com/user-attachments/assets/7393a98b-d085-4235-925a-9a6d3a1f2a89)

**Comment by SolidBlock-cn** [comment]
目前还是无法复现。有截图吗？

**Comment by specialTT** [comment]
似乎是其他模組或數據包、資源包導致的問題，我之前移除了一些模組，現在不會了，看來不是這個模組本身的問題。
我猜測有可能是有個知名模組造成的(因為也有人有相同的問題)。
