### ISSUE TITLE
Button texture missing for all buttons

### ISSUE THREAD

**Issue by sam-snyder** [SolidBlock-cn/extshape#66]
Minecraft version 1.21.1
Fabric Version 0.16.7
Blockus 2.9.5
Extended 3.0.2

![image](https://github.com/user-attachments/assets/23e21f1c-8dfb-4400-abe3-1d49237beafa)

**Comment by SolidBlock-cn** [comment]
Oh my god it looks like a huge fault. I'll check and fix it.

**Comment by SolidBlock-cn** [comment]
I tested just now and could not reproduce the issue. Could you use version 3.0.4 of the Extended Block Shapes mod?

**Comment by sam-snyder** [comment]
Sure, where can I find 3.0.4?

I have a massive pack so its probably another mod conflicting. Let me do some more troubleshooting.

**Comment by sam-snyder** [comment]
Ok I found the conflict.
My bad, sorry to waste your time.

It was Arcle's Medieval Containers Resource Pack.
