### ISSUE TITLE
Wool Carpets Recipe Conflict

### ISSUE THREAD

**Issue by Syhlo** [SolidBlock-cn/extshape#7]
### Minecraft Version
1.17 & 1.17.1

### Extshape Version
1.2.6

### Issue Description
The crafting recipe for wool pressure plates conflicts with the vanilla recipe to craft carpets; this prevents the ability to create carpets entirely.

**Comment by xanthian** [comment]
Only seems to be concurring for pink and red wool for me

**Comment by SolidBlock-cn** [comment]
Fixed. Now a pressure plate is crafted from a carpet.
