### ISSUE TITLE
Cannot Craft Lapis Block to Lapis item

### ISSUE THREAD

**Issue by ClaudiusMinimus** [SolidBlock-cn/extshape#8]
After crafting what I thought was a vanilla Lapis Block [minecraft:lapis_block], when I tried to change the Lapis block back to Lapis Lazuli  [minecraft:lapis_lazuli], but it will only craft to a Lapis Button [extshape:lapis_button]

Minecraft: snapshot 21w43a [1.18-alpha.21.43.a]
extshape-1.3.0-mc1.17

**Comment by ClaudiusMinimus** [comment]
I should also mention Polymorph is not available in 1.18 yet, which would provide a workaround

**Comment by ClaudiusMinimus** [comment]
I found a workaround by using the [Simple Uncrafting Table (Fabric](https://www.curseforge.com/minecraft/mc-mods/simple-uncrafting-table-fabric).

BTW: I am including your mod for my 99 Mods on the Wall: Fabric Edition, which will be on Curseforge soon. My [99 Mods on the Wall: Forge version](https://www.curseforge.com/minecraft/modpacks/ninety-nine-mods-on-the-wall) has gotten close to 7,000 downloads.

**Comment by ClaudiusMinimus** [comment]
This issue also affects diamonds and emeralds. It may well include other blocks as well.

**Comment by SolidBlock-cn** [comment]
Fixed. They are not craftable now.
